openapi: 3.0.0
info:
  title: UMC Study API
  version: 1.0.0
  description: UMC Study API with express, API 설명
servers:
  - url: http://localhost:3000
paths:
  /store/add:
    post:
      summary: 지역 가게 추가
      tags:
        - Store
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                region_id:
                  type: integer
                  example: 1
                  description: 가게가 속한 지역 ID
                name:
                  type: string
                  example: 갓청자 팝업 스토어
                  description: 가게 이름
                address:
                  type: string
                  example: 서울시 송파구 충민로
                  description: 가게 주소
                star_rating:
                  type: number
                  format: float
                  example: 4.5
                  description: 가게 별점
      responses:
        '200':
          description: 성공적으로 추가 되었습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: success!
                  result:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      region_id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 추가한 가게명
                      address:
                        type: string
                        example: 가게의 주소
                      star_rating:
                        type: number
                        format: float
                        example: 4.5
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다.
        '409':
          description: 가게 중복시 충돌 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: STORE5001
                  message:
                    type: string
                    example: 이미 존재하는 가게 입니다.
                  details:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: 이미 존재하는 가게 ID
                      region_id:
                        type: integer
                        description: 존재하는 가게 지역 ID
                      name:
                        type: string
                        description: 가게 이름
                      address:
                        type: string
                        description: 가게 주소
                      star_rating:
                        type: number
                        format: float
                        description: 별점
                      created_at:
                        type: string
                        format: date-time
                        description: 추가된 시간
                      updated_at:
                        type: string
                        format: date-time
                        description: 업데이트 된 시간
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.
