openapi: 3.0.0
info:
  title: UMC Study API
  version: 1.0.0
  description: UMC Study API with express, API 설명
servers:
  - url: http://localhost:3000
paths:
  /store/add:
    post:
      summary: Add a new store
      tags:
        - Store
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                region_id:
                  type: integer
                  example: 1
                  description: ID of the region where the store is located
                name:
                  type: string
                  example: Sample Store
                  description: Name of the store
                address:
                  type: string
                  example: 123 Sample Street
                  description: Address of the store
                star_rating:
                  type: number
                  format: float
                  example: 4.5
                  description: Star rating of the store
      responses:
        '200':
          description: Store created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: success!
                  result:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 123
                      region_id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: sp Store
                      address:
                        type: string
                        example: 123 Sample Street
                      star_rating:
                        type: number
                        format: float
                        example: 4.5
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다.
  /store/review:
    post:
      summary: Add a new review to a store
      tags:
        - Store
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                store_id:
                  type: integer
                  example: 1
                  description: ID of the store being reviewed
                user_id:
                  type: integer
                  example: 1
                  description: ID of the user adding the review
                body:
                  type: string
                  example: 리뷰내용
                  description: The content of the review
                star_rating:
                  type: number
                  format: float
                  example: 4.5
                  description: The star rating of the review
      responses:
        '200':
          description: Review added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 123
                    description: ID of the created review
                  store_id:
                    type: integer
                    example: 1
                    description: ID of the store being reviewed
                  user_id:
                    type: integer
                    example: 1
                    description: ID of the user adding the review
                  body:
                    type: string
                    example: 맛없어요
                    description: The content of the review
                  star_rating:
                    type: number
                    format: float
                    example: 4.5
                    description: The star rating of the review
                  created_at:
                    type: string
                    format: date-time
                    example: 2024-06-08T12:34:56Z
                    description: Review creation timestamp
                  updated_at:
                    type: string
                    format: date-time
                    example: 2024-06-08T12:34:56Z
                    description: Review last update timestamp
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다.
  /mission/add:
    post:
      summary: Add a new mission to a store
      tags:
        - Mission
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                store_id:
                  type: integer
                  example: 1
                  description: ID of the store for the mission
                reward:
                  type: integer
                  example: 1000
                  description: Reward for completing the mission
                body:
                  type: string
                  example: 미션 내용
                  description: The content of the mission
      responses:
        '200':
          description: Mission added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                    description: ID of the created mission
                  mission_id:
                    type: integer
                    example: 1
                    description: ID of the mission
                  store_id:
                    type: integer
                    example: 1
                    description: ID of the store for the mission
                  reward:
                    type: integer
                    example: 1000
                    description: Reward for completing the mission
                  body:
                    type: string
                    example: 미션 내용
                    description: The content of the mission
                  created_at:
                    type: string
                    format: date-time
                    example: 2024-06-08T12:34:56Z
                    description: Mission creation timestamp
                  updated_at:
                    type: string
                    format: date-time
                    example: 2024-06-08T12:34:56Z
                    description: Mission last update timestamp
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다.
        '409':
          description: Conflict - Mission already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 409
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: "MISSSION001"
                  message:
                    type: string
                    example: "이미 존재하는 미션 입니다."
components:
  schemas:
    Store:
      type: object
      properties:
        id:
          type: integer
          description: ID of the store
        region_id:
          type: integer
          description: ID of the region where the store is located
        name:
          type: string
          description: Name of the store
        address:
          type: string
          description: Address of the store
        star_rating:
          type: number
          format: float
          description: Star rating of the store
        created_at:
          type: string
          format: date-time
          description: Store creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Store last update timestamp
    Review:
      type: object
      properties:
        id:
          type: integer
          description: ID of the review
        store_id:
          type: integer
          description: ID of the store being reviewed
        user_id:
          type: integer
          description: ID of the user adding the review
        body:
          type: string
          description: The content of the review
        star_rating:
          type: number
          format: float
          description: The star rating of the review
        created_at:
          type: string
          format: date-time
          description: Review creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Review last update timestamp
    Mission:
      type: object
      properties:
        id:
          type: integer
          description: ID of the mission
        mission_id:
          type: integer
          description: ID of the mission
        store_id:
          type: integer
          description: ID of the store for the mission
        reward:
          type: integer
          description: Reward for completing the mission
        body:
          type: string
          description: The content of the mission
        created_at:
          type: string
          format: date-time
          description: Mission creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Mission last update timestamp
